image: rust:1.70

stages:
  - lint_test
  - build

lint_test:
    stage: lint_test
    cache:
        paths:
            - target/
    script:
        - rustup component add clippy
        - cargo clippy -- -Dwarnings
        - echo "Testing"
        - cargo test --verbose
    

build:
    stage: build
    script:
        - echo "Building"
        - cargo build --verbose
    cache:
        paths:
            - target/