stages:
  - lint_test
  - build

lint_test:
    stage: lint_test
    image: rust:1.70
    script:
        - echo "Linting"
        - rustup component add clippy
        - cargo clippy -- -Dwarnings
        - echo "Testing"
        - cargo test --verbose

build:
    stage: build
    image: rust:1.70
    cache:
        paths:
            - target/
    script:
        - echo "Building"
        - cargo build --verbose