[package]
name = "blockchain-solana"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-sdk = "1.16.2"

mpc-rocket = { git = "https://github.com/can-arikan/my-rust-rocket.git" } # CANIN ULTRA SUPER LIBLERI

tokio = "1.28.2"